export * from "./getDisability.service";
export * from "./getEthnics.service";
export * from "./getGenders.service";
export * from "./getMaritalStatus.service";
export * from "./getRoles.service";
export * from "./getUsers.service";
export * from "./patchToggleUserState.service";
export * from "./postRegister.service";
export * from "./putRegister.service";
