export enum APP_ROLES {
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
  USER = "USER",
  POLICE = "POLICE",
  MEDIC = "MEDIC"
}

export const ADMIN_ROLES = [APP_ROLES.ADMIN, APP_ROLES.SUPER_ADMIN, APP_ROLES.POLICE];
export const USER_ROLES = [APP_ROLES.USER];
