export enum APP_ROLES {
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
  USER = "USER",
  WATCHMAN = "WATCHMAN"
}

export const ADMIN_ROLES = [APP_ROLES.ADMIN, APP_ROLES.SUPER_ADMIN, APP_ROLES.WATCHMAN];
export const USER_ROLES = [APP_ROLES.USER];
